# Generated by Django 5.0.2 on 2024-03-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_orders_product_orders_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_quantity',
        ),
    ]
