# Generated by Django 5.0.2 on 2024-03-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_orders_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='time',
        ),
        migrations.AddField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
