# Generated by Django 5.0.2 on 2024-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_orders_date_remove_orders_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='datetime',
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
