# Generated by Django 5.0.2 on 2024-03-13 13:45

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_orders_datetime_orders_date_orders_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.CharField(max_length=50, null=True, verbose_name=dashboard.models.Product),
        ),
    ]
