# Generated by Django 5.0.2 on 2024-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_orders_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
