# Generated by Django 5.0.2 on 2024-03-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_orders_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
