# Generated by Django 5.0.2 on 2024-03-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subject',
            new_name='division',
        ),
    ]
