# Generated by Django 5.0.2 on 2024-03-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_subject_profile_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='division',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Junior HS', 'Junior HS'), ('Senior HS', 'Senior HS'), ('Science Teacher', 'Science Teacher')], default='Science Teacher', max_length=20),
        ),
    ]
